#Minecraft server properties
#Thu Mar 05 21:51:52 UTC 2026
spawn-protection=0
max-tick-time=600000
query.port=9898
generator-settings=
force-gamemode=false
allow-nether=true
enforce-whitelist=false
gamemode=0
broadcast-console-to-ops=true
enable-query=true
player-idle-timeout=30
difficulty=3
spawn-monsters=true
op-permission-level=4
resource-pack-hash=
announce-player-achievements=true
pvp=true
snooper-enabled=true
level-type=flat
hardcore=false
enable-command-block=true
max-players=20
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=14061
debug=false
server-ip=
spawn-npcs=true
allow-flight=true
level-name=lobby
view-distance=8
resource-pack=
spawn-animals=true
white-list=false
generate-structures=false
max-build-height=256
online-mode=false
level-seed=
use-native-transport=false
motd=\u00A77\u00A1Bienvenido al servidor de \u00A79JeshuaZXH\u00A77\!
enable-rcon=false
